### ISSUE TITLE
ES5

### ISSUE THREAD

**Issue by princed** [posthtml/posthtml-loader#2]
Would you mind to merge a pull request with downgrade to ES5 to make this module compatible with older node.js versions?

**Comment by michael-ciniawsky** [comment]
hi sry for the late reply no pull request are always welcome

**Comment by GitScrum** [comment]
@princed actuality ?

**Comment by princed** [comment]
Sure, merge it, please.

**Comment by michael-ciniawsky** [comment]
Hi, ES5 compatibility should be given since 0.9. Sry this was my fault i oversaw the pull request back then, i will merge it in the 1.0 release in the next few days up ahead, but i'm currently finishing the autoloading options/plugins/presets plugins for posthtml, which will be part of the 1.0 release

**Comment by GitScrum** [comment]
@princed  update and enjoy :)

**Comment by princed** [comment]
@GitScrum Great, thanks!
